### ISSUE TITLE
Alternate stock/page size?

### ISSUE THREAD

**Issue by oneilsh** [EricMarcon/memoiR#1]
Hi, thank you for working on this! I've been looking for an option for both beautiful online and PDF book development for the second edition of my open-access textbook which also has a print-on-demand version. 

Do you know how I might get this template to use alternative stock sizes? I'm no memoir expert but I managed to adjust [this one](https://tex.stackexchange.com/a/46243) which is quite nice for crown quatro size by using

```
\setstocksize{25.2cm}{19.5cm}{*}
\settrimmedsize{24.6cm}{18.9cm}{*}
\settrims{0.318cm}{0.318cm}

\setlxvchars
\settypeblocksize{*}{1.2\lxvchars}{*}

\setlrmargins{*}{*}{1.5}
\setulmarginsandblock{1in}{1in}{1.2}
\checkandfixthelayout 
```

When I try and modify the template.tex here (I just replaced the set and check commands in the `\newcommand*{\SmallMargins}` section) the content resizes ok but the stock stays at 8.5x11.

**Comment by EricMarcon** [comment]
The short answer is "don't modify template.tex" because the main point of this package is to avoid that.

The stock size is set in the `papersize` option in the header of `index.Rmd`. Any size accepted by the LaTeX memoir class can be chosen, see tables 1.1 to 1.3 in the [memoir manual](https://mirrors.ctan.org/tex-archive/macros/latex/contrib/memoir/memman.pdf). 
Basically, the paper (logical) and stock (physical, in the printer) sizes are the same.
So, if both memoir and your printer accept it, you just have to enter the proper paper(=stock) size.
Unfortunately, crown quarto is not in the list.

For advanced users, any paper size can be chosen by trimming the stock as of version 1.0-0.9001 (install it from GitHub). See the [customisation article](https://ericmarcon.github.io/memoiR/dev/articles/articles/memoir.html), section "Paper and stock size" to see how.
In you case, assuming an A4 stock printer, you'll have

```
(...)
classoption:
(...)
  - showtrims
(...)  
papersize: A4
(...)
# Margins
largemargins: false
smallmargin: 1.5in
(...)
spinemargin: 1.5in
(...)
uppermargin: 1in
lowermargin: 1in
(...)
```

in `index.Rmd` to chose the stock size, and 
```
\settrimmedsize{24.6cm}{18.9cm}{*} % Crown quarto
\settrims{0.318cm}{0.318cm}        % Arbitrary left and top trims
```

in `latex/preamble.text` to trim it.

The margin sizes are chosen independently from the paper size.
