### ISSUE TITLE
Currently not working with issues with polyglossa

### ISSUE THREAD

**Issue by fsgiGH** [EricMarcon/memoiR#2]
However trying to get around it... currently memoiR is unable to produce pdf files under RStudio with bookdown/knitr due to errors with polyglossa. Rumors are that pandoc is no longer supporting it, and memoiR relies on polyglossa. Just to let you know.

**Comment by EricMarcon** [comment]
The issue is in polyglossia 1.55a. It has been corrected in v. 1.56, see [this issue](https://github.com/reutenauer/polyglossia/issues/539). Now we have to wait for v. 1.56 to be available on CTAN and update.
Hopefully, pandoc will keep support polyglossia in the future. Since [version 2.15](https://pandoc.org/releases.html#pandoc-2.15-2021-10-23), babel is used by default in native pandoc LaTeX templates to simplify the package selection according to the LaTeX engine (pfdlatex, xelatex...). But memoiR uses custom templates that use only xelatex and rely on polyglossia so that the language selection (`lang: en-US`) is identical for PDF (through LaTeX ) and HTML outputs.

**Comment by fsgiGH** [comment]
Thank you so much for the reply, then let's wait! It is a pity, because
your templates are really fantastic and it is a shame not to be able to use
them for pdfs currently!

Best regards

Fabio

Il mer 20 apr 2022, 15:19 Eric Marcon ***@***.***> ha scritto:

**Comment by EricMarcon** [comment]
polyglossia 1.56 is out and mirrored on CTAN.
memoiR package check passes again.
