### ISSUE TITLE
Can I add a logo to top left hand side of each page

### ISSUE THREAD

**Issue by tanga94** [EricMarcon/memoiR#3]
Hi @EricMarcon , thanks for making this package available I'm really a fan of the stylish article template.

I was wondering, is there any way to add a company logo to the top left corner of each page (besides the cover/first page)?

Thanks!

**Comment by EricMarcon** [comment]
I assume we are considering the "memoir" template.
This is out of the scope of the package but you may add $\LaTeX$ code in the preamble (`latex/preambme.tex`).
According to [memoir's manual](https://mirror.ibcp.fr/pub/CTAN/macros/latex/contrib/memoir/memman.pdf), page headers have three parts: left, center and right (section 7.2, page 108). They are defined in their respective page style, that you choose in the header of `index.Rmd` in your project, that is 'Ruled' by default (around line 55):

> MemoirPageStyle: Ruled             # or companion with large margins

In `latex/preambme.tex`, add:
> \makeoddhead  {Ruled}{\includegraphics[height=0.3in]{logo}}{}{\rightmark}

This redefines the header of odd pages. 
`\makeoddhead` has 4 arguments: the page style's name, the left, the center and the right part.
The logo (`image/logo.pdf`, but the folder is by default and `.pdf` is implicit) is added on the left part. The right part contains the "right mark", i.e. the section number and title in this page style.

You'll get this:

![logo_on_top_left](https://user-images.githubusercontent.com/29632125/211392891-8e11f263-d50d-418a-86df-93234162889c.png)

Note that the logo is small (0.3 inches) because a bigger logo increases the header's size and the header writes over the text. You may play with margin sizes: see memoir's manual, but this is quite a pain.

The even page header is not modified because its left part contains the chapter's name and has no room for a logo. You may place the logo to the right, add:

> \makeevenhead {Ruled}{\scshape\leftmark}{}{\includegraphics[height=0.3in]{logo}}

If you change the page style in `index.Rmd`, you must change the LaTeX commands accordingly. Copy their default value from the manual, and add the logo.

You may choose another approach by adding whatever LaTeX code in the preamble. If you do not use the header but a filigrane, you may be able to display bigger logos behinf the text, but this may be tricky to find the appropriate code and to recognize text pages and avoid title pages. You may need a $\LaTeX$ expert to help you.

**Comment by tanga94** [comment]
Hi @EricMarcon , thanks for the response! I was referring to the Stylish Article template (https://ericmarcon.github.io/memoiR/gallery/stylish_article/bookdown_pdf_book/stylish_article.pdf)

I suppose I could try to apply something similar in the ```stylish_article.tex``` template in the latex subfolder?

Many thanks once again!

**Comment by EricMarcon** [comment]
The strategy is the same, but the template is different. *Stylish article* is an article class that uses the *fancyhdr* LaTeX package.

You must add a command to the preamble to include the logo in the left part of the header (`\lhead{}`). Before that, you can easily increase the height of the header.
The preamble is not in a separate file but in the header of the main .Rmd file (close to line 40). You just need to add the commands there:

>   \setlength\headheight{1.5cm}
>  \lhead{\includegraphics[width=1cm]{images/logo}}

Note that you need write the path to the image there.

You'll get:
![logo_on_top_left_stylish](https://user-images.githubusercontent.com/29632125/211562523-dc8a27c4-029a-47e3-a54b-e6aa4a41a039.png)

**Comment by tanga94** [comment]
Hi @EricMarcon , this is a perfect solution! Thanks so much for the assistance, much appreciated
